SearchDefinitions:
 moduleName: rainmaker-pt-gissearch
 summary: Searcher configuration for Adhoc Requirment
 version: 1.0.0
 definitions:

 - name: searchNewTaxPayments
   query:
    baseQuery: |
      select array_to_json(array_agg(row_to_json(data))) from (
        select
          pt.propertyid as propertyid,
          pt.oldpropertyid as oldpropertyid,
          pd.receiptnumber as receiptnumber,
          pt.tenantid as tenantid,
          pd.receiptdate as receiptdate, 
          bn.blockname
        from egcl_paymentdetail AS pd
        INNER JOIN egcl_bill on pd.billid=egcl_bill.id
        INNER JOIN eg_pt_property AS pt ON pt.propertyid = egcl_bill.consumercode AND pt.oldpropertyid IS NOT NULL
        AND pt.oldpropertyid != ''
        INNER JOIN eg_pt_address As ad ON ad.propertyid=pt.id and ad.lastmodifiedtime in (select max(lastmodifiedtime) from eg_pt_address where propertyid=pt.id)
        INNER JOIN  eg_bndry_mohalla  As bn ON ad.locality=bn.localitycode and ad.tenantid=bn.tenantid $where) data
    groupBy:
    orderBy:
   searchParams:
    condition: AND
    params:
    - name: pd.receiptdate
      isMandatory: false
      jsonPath: $.searchCriteria.fromDate
      operator: GE
    - name: pd.receiptdate
      isMandatory: false
      jsonPath: $.searchCriteria.toDate
      operator: LE
    - name: pt.tenantid
      isMandatory: true
      jsonPath: $.searchCriteria.tenantId
      operator: =
    - name: bn.blockname
      isMandatory: false
      jsonPath: $.searchCriteria.blockcode
      operator: =


   output:
    jsonFormat: {"ResponseInfo": {}}
    outJsonPath: $.data
    responseInfoPath: $.ResponseInfo
    
 - name: firenoc_billing_slab_search
   query:
    baseQuery: |
      select array_to_json(array_agg(row_to_json(data))) from (
        SELECT * FROM eg_firenoc_state_billingslab 
        $where) data
    groupBy:
    orderBy:
   searchParams:
    condition: AND
    params:
    - name: heightfromuom
      isMandatory: true
      jsonPath: $.searchCriteria.height
      operator: LE
    - name: heighttouom
      isMandatory: true
      jsonPath: $.searchCriteria.height
      operator: GE
    - name: buildingusagetype
      isMandatory: true
      jsonPath: $.searchCriteria.usagetype
      operator: =

   output:
    jsonFormat: {"ResponseInfo": {}}
    outJsonPath: $.data
    responseInfoPath: $.ResponseInfo
    
    
 - name: searchTLApplicationsEODB
   query:
    baseQuery: |
      select array_to_json(array_agg(row_to_json(data))) from (
        select 
          tl.applicationnumber,
          tld.additionalDetail::text,
          tl.status,additionalDetail->>'IPIN' as iPin,
          additionalDetail->>'APPID' as appId,
          additionalDetail->>'mobileNo' as mobileNp 
        from eg_tl_tradelicense tl 
        inner join eg_tl_tradelicensedetail tld on tld.tradelicenseid=tl.id and tld.additionalDetail->>'CHANNEL'='EODB' $where) data
    groupBy:
    orderBy:
   searchParams:
    condition: AND
    params:
    - name: tl.tenantid
      isMandatory: false
      jsonPath: $.searchCriteria.tenantId
      operator: =
    
   output:
    jsonFormat: {"ResponseInfo": {}}
    outJsonPath: $.data
    responseInfoPath: $.ResponseInfo
