SearchDefinitions:
 moduleName: rainmaker-pt-gissearch
 summary: Searcher configuration for Adhoc Requirment
 version: 1.0.0
 definitions:

 - name: searchNewTaxPayments
   query:
    baseQuery: |
      select array_to_json(array_agg(row_to_json(data))) from (
        select
           concat(pt.propertyid , '/' , pt.surveyid) as primarykey,
           pt.oldpropertyid as oldpropertyid,
           pt.surveyid as surveyid,
           pd.amountpaid as amount,
           getfinancialyearforgis(pd.billid) as financialyear,
           bn.blockname,
           pt.tenantid as tenantid,
           pd.receiptnumber as receiptnumber,
           to_char(to_timestamp(cast(pd.receiptdate/1000 as bigint))::date , 'dd/mm/yyyy') as receiptdate,
           pt.landarea as plotarea
        from egcl_paymentdetail AS pd
        INNER JOIN egcl_bill on pd.billid=egcl_bill.id
        INNER JOIN eg_pt_property AS pt ON pt.propertyid = egcl_bill.consumercode AND  ((pt.oldpropertyid IS NOT NULL
        AND pt.oldpropertyid != '') OR pt.surveyid is not null)
        INNER JOIN eg_pt_address As ad ON ad.propertyid=pt.id and ad.lastmodifiedtime in (select max(lastmodifiedtime) from eg_pt_address where propertyid=pt.id)
        INNER JOIN  eg_bndry_mohalla  As bn ON ad.locality=bn.localitycode and ad.tenantid=bn.tenantid $where) data
    groupBy:
    orderBy:
   searchParams:
    condition: AND
    params:
    - name: pd.receiptdate
      isMandatory: false
      jsonPath: $.searchCriteria.fromDate
      operator: GE
    - name: pd.receiptdate
      isMandatory: false
      jsonPath: $.searchCriteria.toDate
      operator: LE
    - name: pt.tenantid
      isMandatory: true
      jsonPath: $.searchCriteria.tenantId
      operator: =
    - name: bn.blockname
      isMandatory: false
      jsonPath: $.searchCriteria.blockcode
      operator: =


   output:
    jsonFormat: {"ResponseInfo": {}}
    outJsonPath: $.data
    responseInfoPath: $.ResponseInfo
